"""about field

Revision ID: cec16ea657ed
Revises: 6fac8b5d6504
Create Date: 2022-03-17 22:11:18.538637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec16ea657ed'
down_revision = '6fac8b5d6504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('about', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'about')
    # ### end Alembic commands ###
